In [3]:
import numpy as np 
import pandas as pd

# Theory

## Question 1

- materials/lecture_notes.pdf pages: 13 - 15

## Question 2

- materials/Pankr_Nedashkov_posibnik.pdf pages: 16 - 18

# Practice

In [4]:
def is_transitive(matrix):
    n = len(matrix)  # Assuming the matrix is square and non-empty
    
    # Check every combination of i, j, and k
    not_trasitive_list = []
    for i in range(n):
        for j in range(n):
            for k in range(n):
                if matrix[i][k] * matrix[k][j] != matrix[i][j]:
                    not_trasitive_list.append((i + 1,k + 1,j + 1))
    if len(not_trasitive_list) == 0:
        return True
    else:
        return not_trasitive_list

## Question 3

In [5]:
d = np.array([
    [1 ,3, 3],
    [1/3, 1, 3],
    [1/3, 1/3, 1]
])
n = len(d)
d

array([[1.        , 3.        , 3.        ],
       [0.33333333, 1.        , 3.        ],
       [0.33333333, 0.33333333, 1.        ]])

In [6]:
is_transitive(d)

[(1, 3, 2), (1, 2, 3), (2, 3, 1), (2, 1, 3), (3, 2, 1), (3, 1, 2)]

In [8]:
s = d.sum(axis=0)
s

array([1.66666667, 4.33333333, 7.        ])

In [9]:
w = 1/s
w

array([0.6       , 0.23076923, 0.14285714])

In [10]:
w_normed = w / w.sum()
w_normed

array([0.61625282, 0.23702032, 0.14672686])

In [11]:
w.sum()

0.9736263736263737

In [14]:
hm = n * (1 / w.sum())
hm

3.081264108352144

In [15]:
hci = ((hm - n) * (n + 1)) / n * (n - 1)
hci

0.21670428893905105

In [16]:
mrci_table = [0, 0, 0, 0.52, 0.89, 1.11, 1.25]

In [17]:
hci / mrci_table[n]

0.4167390171904828

## Question 4

In [18]:
d = np.array([
    [1 ,1/3, 1/3],
    [3, 1, 1/3],
    [3, 3, 1]
])
n = len(d)
d

array([[1.        , 0.33333333, 0.33333333],
       [3.        , 1.        , 0.33333333],
       [3.        , 3.        , 1.        ]])

In [19]:
is_transitive(d)

(1, 3, 2)

In [20]:
w = np.prod(d, axis=1) ** (1/n)
w

array([0.48074986, 1.        , 2.08008382])

In [21]:
w_normed = w / w.sum()
w_normed

array([0.13501048, 0.28083311, 0.58415641])

In [22]:
gci = 0

# Sum only elements where i < j
for i in range(n):
    for j in range(i + 1, n):
        gci += (np.log(d[i][j]) - np.log(w[i] / w[j])) ** 2
        
gci *= (2 / (n -1) * (n-2))

gci

0.40231632027086073

In [23]:
R = np.array([
    [3, 4, 1],
    [1, 3, 2],
    [2, 2, 4],
    [4, 1, 3]
])
R

array([[3, 4, 1],
       [1, 3, 2],
       [2, 2, 4],
       [4, 1, 3]])

In [24]:
R.sum(axis=0, keepdims=True)

array([[10, 10, 10]])

In [25]:
R_normed = R / R.sum(axis=0, keepdims=True)
R_normed

array([[0.3, 0.4, 0.1],
       [0.1, 0.3, 0.2],
       [0.2, 0.2, 0.4],
       [0.4, 0.1, 0.3]])

In [26]:
w_glob = R_normed @ w_normed
w_glob

array([0.21125203, 0.21458226, 0.31683128, 0.25733443])

In [27]:
w_glob / w_glob.sum()

array([0.21125203, 0.21458226, 0.31683128, 0.25733443])